CREATE TABLE IF NOT EXISTS Instances (
  idInstance int(10) unsigned NOT NULL AUTO_INCREMENT,
  active char(1) CHARACTER SET ascii NOT NULL DEFAULT 'Y',
  idProfile int(6) unsigned zerofill NOT NULL,
  instanceType varchar(32) CHARACTER SET ascii DEFAULT NULL,
  instanceName varchar(32) CHARACTER SET ascii NOT NULL,
  amiName varchar(32) CHARACTER SET ascii NOT NULL,
  akiName varchar(32) CHARACTER SET ascii NOT NULL,
  regionName varchar(32) CHARACTER SET ascii NOT NULL,
  availabilityZone varchar(32) CHARACTER SET ascii NOT NULL,
  reservationId varchar(32) CHARACTER SET ascii NOT NULL,
  ownerId varchar(32) CHARACTER SET ascii NOT NULL,
  launchTime varchar(32) CHARACTER SET ascii NOT NULL,
  privateDnsName varchar(512) CHARACTER SET ascii DEFAULT NULL,
  dnsName varchar(512) CHARACTER SET ascii DEFAULT NULL,
  instanceStateCode int(10) NOT NULL,
  instanceStateName varchar(32) CHARACTER SET ascii NOT NULL,
  stateLastUpdated datetime DEFAULT NULL,
  added datetime NOT NULL,
  updated datetime NOT NULL,
  PRIMARY KEY (idInstance),
  KEY added (added),
  KEY updated (updated),
  KEY idProfile (idProfile),
  KEY instanceType (instanceType),
  KEY instanceName (instanceName),
  KEY amiName (amiName),
  KEY akiName (akiName),
  KEY reservationId (reservationId),
  KEY ownerId (ownerId),
  KEY instanceStateCode (instanceStateCode),
  KEY instanceStateName (instanceStateName),
  KEY stateLastUpdated (stateLastUpdated),
  KEY active (active)
) ENGINE=InnoDB;
